version: "3.1"
services:

  zeppelin:
    image: zeppelin:latest
    privileged: true
    hostname: zeppelin
    container_name: zeppelin
    ports:
      - "9010:9010"
    depends_on:
      - master
      - worker
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
      - ./docker/zeppelin/conf:/opt/zeppelin-0.9.0-bin-all/conf
      - ./docker/zeppelin/local-repo:/opt/zeppelin-0.9.0-bin-all/local-repo
    #  /opt/zeppelin-0.9.0-bin-all/bin/zeppelin-daemon.sh start

  master:
    image: spark-master:latest
    privileged: true
    hostname: master
    container_name: master
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - "4040:4040"
      - "8080:8080"
      - "7077:7077"
      - "6066:6066"
      - "18080:18080"
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
    environment:
      - "SPARK_PUBLIC_DNS=localhost"
      - "MASTER=spark://master:7077"

  worker:
    image: spark-worker:latest
    privileged: true
    hostname: worker
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    depends_on:
      - master
    environment:
      - "SPARK_MASTER=spark://master:7077"
      - "SPARK_WORKER_CORES=1"
      - "SPARK_WORKER_MEMORY=1G"
      - "SPARK_EXECUTOR_MEMORY=512m"
      - "SPARK_WORKER_PORT=8881"
      - "SPARK_WORKER_WEBUI_PORT=8081"
      - "SPARK_PUBLIC_DNS=worker"
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
